# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\cygwin64\home\traceur\projects\NetL

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\cygwin64\home\traceur\projects\NetL

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\cygwin64\home\traceur\projects\NetL\CMakeFiles C:\cygwin64\home\traceur\projects\NetL\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\cygwin64\home\traceur\projects\NetL\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named NetLnet

# Build rule for target.
NetLnet: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 NetLnet
.PHONY : NetLnet

# fast build rule for target.
NetLnet/fast:
	$(MAKE) $(MAKESILENT) -f NetL\CMakeFiles\NetLnet.dir\build.make NetL/CMakeFiles/NetLnet.dir/build
.PHONY : NetLnet/fast

#=============================================================================
# Target rules for targets named NetLbase

# Build rule for target.
NetLbase: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 NetLbase
.PHONY : NetLbase

# fast build rule for target.
NetLbase/fast:
	$(MAKE) $(MAKESILENT) -f Base\CMakeFiles\NetLbase.dir\build.make Base/CMakeFiles/NetLbase.dir/build
.PHONY : NetLbase/fast

#=============================================================================
# Target rules for targets named ut_EventLoopClass

# Build rule for target.
ut_EventLoopClass: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 ut_EventLoopClass
.PHONY : ut_EventLoopClass

# fast build rule for target.
ut_EventLoopClass/fast:
	$(MAKE) $(MAKESILENT) -f test\UnitTest\CMakeFiles\ut_EventLoopClass.dir\build.make test/UnitTest/CMakeFiles/ut_EventLoopClass.dir/build
.PHONY : ut_EventLoopClass/fast

#=============================================================================
# Target rules for targets named mt_EventLoopClass_01

# Build rule for target.
mt_EventLoopClass_01: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 mt_EventLoopClass_01
.PHONY : mt_EventLoopClass_01

# fast build rule for target.
mt_EventLoopClass_01/fast:
	$(MAKE) $(MAKESILENT) -f test\ManualTest\CMakeFiles\mt_EventLoopClass_01.dir\build.make test/ManualTest/CMakeFiles/mt_EventLoopClass_01.dir/build
.PHONY : mt_EventLoopClass_01/fast

#=============================================================================
# Target rules for targets named mt_EventLoopClass_02

# Build rule for target.
mt_EventLoopClass_02: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 mt_EventLoopClass_02
.PHONY : mt_EventLoopClass_02

# fast build rule for target.
mt_EventLoopClass_02/fast:
	$(MAKE) $(MAKESILENT) -f test\ManualTest\CMakeFiles\mt_EventLoopClass_02.dir\build.make test/ManualTest/CMakeFiles/mt_EventLoopClass_02.dir/build
.PHONY : mt_EventLoopClass_02/fast

#=============================================================================
# Target rules for targets named mt_EventLoop+PollPoller+Channel_01

# Build rule for target.
mt_EventLoop+PollPoller+Channel_01: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 mt_EventLoop+PollPoller+Channel_01
.PHONY : mt_EventLoop+PollPoller+Channel_01

# fast build rule for target.
mt_EventLoop+PollPoller+Channel_01/fast:
	$(MAKE) $(MAKESILENT) -f test\ManualTest\CMakeFiles\mt_EventLoop+PollPoller+Channel_01.dir\build.make test/ManualTest/CMakeFiles/mt_EventLoop+PollPoller+Channel_01.dir/build
.PHONY : mt_EventLoop+PollPoller+Channel_01/fast

#=============================================================================
# Target rules for targets named mt_EventLoopClass_03

# Build rule for target.
mt_EventLoopClass_03: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 mt_EventLoopClass_03
.PHONY : mt_EventLoopClass_03

# fast build rule for target.
mt_EventLoopClass_03/fast:
	$(MAKE) $(MAKESILENT) -f test\ManualTest\CMakeFiles\mt_EventLoopClass_03.dir\build.make test/ManualTest/CMakeFiles/mt_EventLoopClass_03.dir/build
.PHONY : mt_EventLoopClass_03/fast

#=============================================================================
# Target rules for targets named mt_EventLoop+PollPoller+Channel

# Build rule for target.
mt_EventLoop+PollPoller+Channel: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 mt_EventLoop+PollPoller+Channel
.PHONY : mt_EventLoop+PollPoller+Channel

# fast build rule for target.
mt_EventLoop+PollPoller+Channel/fast:
	$(MAKE) $(MAKESILENT) -f test\ManualTest\CMakeFiles\mt_EventLoop+PollPoller+Channel.dir\build.make test/ManualTest/CMakeFiles/mt_EventLoop+PollPoller+Channel.dir/build
.PHONY : mt_EventLoop+PollPoller+Channel/fast

main.obj: main.cpp.obj

.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... NetLbase
	@echo ... NetLnet
	@echo ... main
	@echo ... mt_EventLoop+PollPoller+Channel
	@echo ... mt_EventLoop+PollPoller+Channel_01
	@echo ... mt_EventLoopClass_01
	@echo ... mt_EventLoopClass_02
	@echo ... mt_EventLoopClass_03
	@echo ... ut_EventLoopClass
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

