# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\cygwin64\home\traceur\projects\NetL

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\cygwin64\home\traceur\projects\NetL

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\cygwin64\home\traceur\projects\NetL\CMakeFiles C:\cygwin64\home\traceur\projects\NetL\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\cygwin64\home\traceur\projects\NetL\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mtest_EventLoopClass_03

# Build rule for target.
mtest_EventLoopClass_03: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 mtest_EventLoopClass_03
.PHONY : mtest_EventLoopClass_03

# fast build rule for target.
mtest_EventLoopClass_03/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mtest_EventLoopClass_03.dir\build.make CMakeFiles/mtest_EventLoopClass_03.dir/build
.PHONY : mtest_EventLoopClass_03/fast

NetL/Channel.obj: NetL/Channel.cpp.obj

.PHONY : NetL/Channel.obj

# target to build an object file
NetL/Channel.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mtest_EventLoopClass_03.dir\build.make CMakeFiles/mtest_EventLoopClass_03.dir/NetL/Channel.cpp.obj
.PHONY : NetL/Channel.cpp.obj

NetL/Channel.i: NetL/Channel.cpp.i

.PHONY : NetL/Channel.i

# target to preprocess a source file
NetL/Channel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mtest_EventLoopClass_03.dir\build.make CMakeFiles/mtest_EventLoopClass_03.dir/NetL/Channel.cpp.i
.PHONY : NetL/Channel.cpp.i

NetL/Channel.s: NetL/Channel.cpp.s

.PHONY : NetL/Channel.s

# target to generate assembly for a file
NetL/Channel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mtest_EventLoopClass_03.dir\build.make CMakeFiles/mtest_EventLoopClass_03.dir/NetL/Channel.cpp.s
.PHONY : NetL/Channel.cpp.s

NetL/EventLoop.obj: NetL/EventLoop.cpp.obj

.PHONY : NetL/EventLoop.obj

# target to build an object file
NetL/EventLoop.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mtest_EventLoopClass_03.dir\build.make CMakeFiles/mtest_EventLoopClass_03.dir/NetL/EventLoop.cpp.obj
.PHONY : NetL/EventLoop.cpp.obj

NetL/EventLoop.i: NetL/EventLoop.cpp.i

.PHONY : NetL/EventLoop.i

# target to preprocess a source file
NetL/EventLoop.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mtest_EventLoopClass_03.dir\build.make CMakeFiles/mtest_EventLoopClass_03.dir/NetL/EventLoop.cpp.i
.PHONY : NetL/EventLoop.cpp.i

NetL/EventLoop.s: NetL/EventLoop.cpp.s

.PHONY : NetL/EventLoop.s

# target to generate assembly for a file
NetL/EventLoop.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mtest_EventLoopClass_03.dir\build.make CMakeFiles/mtest_EventLoopClass_03.dir/NetL/EventLoop.cpp.s
.PHONY : NetL/EventLoop.cpp.s

NetL/Poller.obj: NetL/Poller.cpp.obj

.PHONY : NetL/Poller.obj

# target to build an object file
NetL/Poller.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mtest_EventLoopClass_03.dir\build.make CMakeFiles/mtest_EventLoopClass_03.dir/NetL/Poller.cpp.obj
.PHONY : NetL/Poller.cpp.obj

NetL/Poller.i: NetL/Poller.cpp.i

.PHONY : NetL/Poller.i

# target to preprocess a source file
NetL/Poller.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mtest_EventLoopClass_03.dir\build.make CMakeFiles/mtest_EventLoopClass_03.dir/NetL/Poller.cpp.i
.PHONY : NetL/Poller.cpp.i

NetL/Poller.s: NetL/Poller.cpp.s

.PHONY : NetL/Poller.s

# target to generate assembly for a file
NetL/Poller.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mtest_EventLoopClass_03.dir\build.make CMakeFiles/mtest_EventLoopClass_03.dir/NetL/Poller.cpp.s
.PHONY : NetL/Poller.cpp.s

test/mtest_EventLoopClass_03.obj: test/mtest_EventLoopClass_03.cpp.obj

.PHONY : test/mtest_EventLoopClass_03.obj

# target to build an object file
test/mtest_EventLoopClass_03.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mtest_EventLoopClass_03.dir\build.make CMakeFiles/mtest_EventLoopClass_03.dir/test/mtest_EventLoopClass_03.cpp.obj
.PHONY : test/mtest_EventLoopClass_03.cpp.obj

test/mtest_EventLoopClass_03.i: test/mtest_EventLoopClass_03.cpp.i

.PHONY : test/mtest_EventLoopClass_03.i

# target to preprocess a source file
test/mtest_EventLoopClass_03.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mtest_EventLoopClass_03.dir\build.make CMakeFiles/mtest_EventLoopClass_03.dir/test/mtest_EventLoopClass_03.cpp.i
.PHONY : test/mtest_EventLoopClass_03.cpp.i

test/mtest_EventLoopClass_03.s: test/mtest_EventLoopClass_03.cpp.s

.PHONY : test/mtest_EventLoopClass_03.s

# target to generate assembly for a file
test/mtest_EventLoopClass_03.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mtest_EventLoopClass_03.dir\build.make CMakeFiles/mtest_EventLoopClass_03.dir/test/mtest_EventLoopClass_03.cpp.s
.PHONY : test/mtest_EventLoopClass_03.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... mtest_EventLoopClass_03
	@echo ... NetL/Channel.obj
	@echo ... NetL/Channel.i
	@echo ... NetL/Channel.s
	@echo ... NetL/EventLoop.obj
	@echo ... NetL/EventLoop.i
	@echo ... NetL/EventLoop.s
	@echo ... NetL/Poller.obj
	@echo ... NetL/Poller.i
	@echo ... NetL/Poller.s
	@echo ... test/mtest_EventLoopClass_03.obj
	@echo ... test/mtest_EventLoopClass_03.i
	@echo ... test/mtest_EventLoopClass_03.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

